In [40]:
import pandas as pd

In [41]:
file_path = ('codebar-AI-fundamentals-pixels-banking-ML-model/data/pixels_banking_loan_repayment_capstone_dataset.csv')

print('Loading file:', file_path)
df = pd.read_csv(file_path)

Loading file: codebar-AI-fundamentals-pixels-banking-ML-model/data/pixels_banking_loan_repayment_capstone_dataset.csv

In [42]:
df.head()

,customer_id,age,region,account_type,tenure_months,monthly_income,avg_monthly_balance,credit_score,num_products,has_credit_card,...,missed_payments_6m,support_rating,contract_type,monthly_fees,digital_engagement_score,loan_amount,loan_term_months,debt_to_income_ratio,interest_rate,loan_repaid
0,PBG-200312,36.0,London,Premium,24,2281.0,1702.0,637.0,3,Yes,...,0,5.0,Annual,16.99,49.0,7500,36,0.36,13.57,0
1,PBG-200958,47.0,South East,Premium,13,4747.0,3045.0,655.0,1,Yes,...,0,NaN,Monthly,16.99,74.0,5000,12,0.14,6.73,1
2,PBG-200402,44.0,West Midlands,Premium,41,5605.0,5230.0,583.0,2,Yes,...,0,2.0,No fixed term,16.99,100.0,3000,48,0.32,12.42,1
3,PBG-200626,49.0,West Midlands,Premium,23,5576.0,7223.0,850.0,3,Yes,...,1,4.0,Monthly,16.99,86.0,15000,48,0.03,3.90,1
4,PBG-200272,32.0,North East,Everyday,63,4737.0,4982.0,691.0,1,No,...,3,4.0,No fixed term,0.00,77.0,10000,12,0.45,7.87,0

In [43]:
missing_values = df.isnull().sum()
missing_values[missing_values > 0].sort_values(ascending=False)

digital_engagement_score    71
avg_monthly_balance         65
support_rating              65
debt_to_income_ratio        43
credit_score                41
interest_rate               36
monthly_income              36
has_credit_card             31
account_type                28
uses_mobile_app             25
age                         24
region                      13
dtype: int64

In [44]:
missing_percent = (df.isnull().sum() / len(df)) * 100
missing_percent[missing_percent > 0].sort_values(ascending=False)

digital_engagement_score    5.916667
avg_monthly_balance         5.416667
support_rating              5.416667
debt_to_income_ratio        3.583333
credit_score                3.416667
interest_rate               3.000000
monthly_income              3.000000
has_credit_card             2.583333
account_type                2.333333
uses_mobile_app             2.083333
age                         2.000000
region                      1.083333
dtype: float64

In [45]:
clean_df = df.copy()

clean_df = clean_df.drop(columns=['customer_id'], errors='ignore')

clean_df.head()

,age,region,account_type,tenure_months,monthly_income,avg_monthly_balance,credit_score,num_products,has_credit_card,has_crypto_wallet,...,missed_payments_6m,support_rating,contract_type,monthly_fees,digital_engagement_score,loan_amount,loan_term_months,debt_to_income_ratio,interest_rate,loan_repaid
0,36.0,London,Premium,24,2281.0,1702.0,637.0,3,Yes,No,...,0,5.0,Annual,16.99,49.0,7500,36,0.36,13.57,0
1,47.0,South East,Premium,13,4747.0,3045.0,655.0,1,Yes,No,...,0,NaN,Monthly,16.99,74.0,5000,12,0.14,6.73,1
2,44.0,West Midlands,Premium,41,5605.0,5230.0,583.0,2,Yes,No,...,0,2.0,No fixed term,16.99,100.0,3000,48,0.32,12.42,1
3,49.0,West Midlands,Premium,23,5576.0,7223.0,850.0,3,Yes,Yes,...,1,4.0,Monthly,16.99,86.0,15000,48,0.03,3.90,1
4,32.0,North East,Everyday,63,4737.0,4982.0,691.0,1,No,Yes,...,3,4.0,No fixed term,0.00,77.0,10000,12,0.45,7.87,0

In [46]:
numeric_columns = clean_df.select_dtypes(include=['int64', 'float64']).columns
categorical_columns = clean_df.select_dtypes(include=['object']).columns

print('Numeric columns:')
print(list(numeric_columns))

print('Categorical columns:')
print(list(categorical_columns))

Numeric columns:
['age', 'tenure_months', 'monthly_income', 'avg_monthly_balance', 'credit_score', 'num_products', 'customer_service_calls', 'missed_payments_6m', 'support_rating', 'monthly_fees', 'digital_engagement_score', 'loan_amount', 'loan_term_months', 'debt_to_income_ratio', 'interest_rate', 'loan_repaid']
Categorical columns:
['region', 'account_type', 'has_credit_card', 'has_crypto_wallet', 'uses_mobile_app', 'contract_type']

In [47]:
flag_columns = ['credit_score', 'monthly_income']
for column in flag_columns:
    clean_df[column + '_was_missing'] = clean_df[column].isnull().astype(int)

In [48]:
for column in numeric_columns:
    median_value = clean_df[column].median()
    clean_df[column] = clean_df[column].fillna(median_value)

In [49]:
for column in categorical_columns:
    clean_df[column] = clean_df[column].fillna("Unknown")

In [50]:
clean_df.isnull().sum().sum()

np.int64(0)

In [51]:
for column in categorical_columns: 
    print(column)
    print(clean_df[column].value_counts())
    print('---')

region
region
London                      205
South East                  155
North West                  120
West Midlands               111
South West                  106
Yorkshire and the Humber     99
East Midlands                97
Scotland                     88
Wales                        83
North East                   80
Northern Ireland             43
Unknown                      13
Name: count, dtype: int64
---
account_type
account_type
Everyday    554
Plus        305
Premium     222
Business     91
Unknown      28
Name: count, dtype: int64
---
has_credit_card
has_credit_card
Yes        669
No         500
Unknown     31
Name: count, dtype: int64
---
has_crypto_wallet
has_crypto_wallet
No     985
Yes    215
Name: count, dtype: int64
---
uses_mobile_app
uses_mobile_app
Yes        899
No         276
Unknown     25
Name: count, dtype: int64
---
contract_type
contract_type
Monthly          445
Annual           421
No fixed term    334
Name: count, dtype: int64
---

In [52]:
df_encoded = pd.get_dummies(
    clean_df,
    columns=categorical_columns,
    drop_first=True
)

df_encoded.head(50)

,age,tenure_months,monthly_income,avg_monthly_balance,credit_score,num_products,customer_service_calls,missed_payments_6m,support_rating,monthly_fees,...,account_type_Plus,account_type_Premium,account_type_Unknown,has_credit_card_Unknown,has_credit_card_Yes,has_crypto_wallet_Yes,uses_mobile_app_Unknown,uses_mobile_app_Yes,contract_type_Monthly,contract_type_No fixed term
0,36.0,24,2281.0,1702.0,637.0,3,3,0,5.0,16.99,...,False,True,False,False,True,False,False,False,False,False
1,47.0,13,4747.0,3045.0,655.0,1,2,0,4.0,16.99,...,False,True,False,False,True,False,False,False,True,False
2,44.0,41,5605.0,5230.0,583.0,2,0,0,2.0,16.99,...,False,True,False,False,True,False,False,True,False,True
3,49.0,23,5576.0,7223.0,850.0,3,2,1,4.0,16.99,...,False,True,False,False,True,True,False,True,True,False
4,32.0,63,4737.0,4982.0,691.0,1,1,3,4.0,0.00,...,False,False,False,False,False,True,False,True,False,True
5,34.0,49,3162.0,2926.0,724.0,1,2,0,4.0,0.00,...,False,False,False,False,True,False,False,True,False,False
6,28.0,76,3003.0,2435.0,754.0,3,2,1,4.0,16.99,...,False,True,False,False,True,False,False,False,False,True
7,54.0,18,3248.0,2305.0,770.0,1,1,0,3.0,16.99,...,False,True,False,False,True,False,False,True,False,False
8,47.0,54,2257.0,282.0,621.0,2,0,2,3.0,7.00,...,True,False,False,False,False,True,False,True,False,True
9,22.0,18,3270.0,1209.0,705.0,3,3,4,5.0,0.00,...,False,False,False,False,True,True,False,True,True,False
10,40.0,38,3673.0,2149.0,514.0,2,1,3,3.0,0.00,...,False,False,False,False,True,False,False,True,True,False
11,21.0,25,4415.0,3332.0,719.0,4,1,1,5.0,0.00,...,False,False,False,False,True,True,False,True,False,True
12,55.0,70,3137.0,3085.0,738.0,2,1,0,3.0,0.00,...,False,False,False,False,True,False,False,True,True,False
13,55.0,26,1458.0,1392.0,685.0,2,3,1,2.0,0.00,...,False,False,False,False,True,True,False,True,False,False
14,29.0,19,900.0,773.0,724.0,1,2,1,3.0,16.99,...,False,True,False,False,True,False,False,False,False,True
15,54.0,11,3016.0,1299.0,747.0,4,3,0,5.0,7.00,...,True,False,False,False,True,False,False,True,False,True
16,29.0,15,4923.0,3569.0,708.0,3,1,0,4.0,16.99,...,False,True,False,False,True,True,False,True,False,True
17,55.0,31,7069.0,2125.0,699.0,3,2,1,4.0,7.00,...,True,False,False,False,True,False,False,True,False,True
18,43.0,33,2768.0,1450.0,668.0,2,0,0,3.0,16.99,...,False,True,False,False,False,False,False,True,True,False
19,41.0,8,4044.0,1620.0,713.0,2,5,0,1.0,0.00,...,False,False,False,False,True,True,False,True,True,False
20,24.0,144,4269.0,1020.0,700.0,3,1,1,4.0,16.99,...,False,True,False,False,True,False,False,True,False,True
21,59.0,35,1100.0,0.0,664.0,1,0,0,4.0,0.00,...,False,False,False,False,False,False,False,True,True,False
22,18.0,14,2822.0,2224.0,674.0,2,3,0,3.0,7.00,...,True,False,False,False,False,False,False,True,True,False
23,49.0,21,5874.0,4542.0,733.0,2,1,0,3.0,16.99,...,False,True,False,False,True,False,False,True,False,False
24,19.0,76,3995.0,2615.0,613.0,1,1,2,3.0,16.99,...,False,True,False,False,True,False,False,True,True,False
25,48.0,120,6876.0,8422.0,573.0,1,2,1,4.0,16.99,...,False,True,False,False,False,False,False,True,False,False
26,30.0,19,2834.0,2563.0,675.0,2,1,0,5.0,16.99,...,False,True,False,False,True,False,False,False,False,False
27,45.0,46,2809.0,3814.0,708.0,3,1,0,3.0,0.00,...,False,False,False,False,False,False,False,True,False,True
28,39.0,101,1189.0,680.0,653.0,2,1,0,1.0,16.99,...,False,True,False,False,True,False,False,True,False,True
29,28.0,106,2860.0,1877.0,511.0,2,1,0,3.0,0.00,...,False,False,False,False,False,True,False,False,False,True
30,42.0,39,3658.0,72.0,721.0,2,0,0,4.0,0.00,...,False,False,False,False,True,False,False,False,False,False
31,28.0,64,4370.0,4286.0,659.0,4,2,1,5.0,7.00,...,True,False,False,False,True,True,False,True,False,False
32,46.0,15,3670.0,2080.0,644.0,4,0,0,4.0,0.00,...,False,False,False,False,True,False,False,True,False,False
33,33.0,23,3157.0,3026.0,842.0,2,0,0,3.0,0.00,...,False,False,False,False,True,True,False,True,False,True
34,42.0,69,5242.0,3261.0,664.0,4,5,0,4.0,0.00,...,False,False,True,False,True,False,False,True,False,False
35,40.0,57,3035.0,1496.0,671.0,1,0,3,4.0,12.00,...,False,False,False,False,False,False,False,True,False,False
36,22.0,26,2117.0,279.0,654.0,1,1,0,4.0,7.00,...,True,False,False,False,True,False,False,True,True,False
37,18.0,50,2970.0,2125.0,762.0,1,3,0,1.0,7.00,...,True,False,False,False,True,True,False,True,True,False
38,53.0,35,2272.0,864.0,634.0,2,3,0,4.0,7.00,...,True,False,False,False,True,False,False,True,False,True
39,25.0,17,5554.0,5716.0,641.0,2,0,0,4.0,0.00,...,False,False,False,False,False,False,False,True,True,False
40,32.0,28,4073.0,3710.0,526.0,3,0,0,2.0,0.00,...,False,False,False,False,False,False,False,True,False,True
41,39.0,34,1608.0,420.0,589.0,1,3,0,5.0,7.00,...,True,False,False,False,True,False,False,False,True,False
42,49.0,74,3998.0,4004.0,668.0,4,1,1,1.0,16.99,...,False,True,False,False,True,True,False,True,True,False
43,32.0,51,1537.0,2074.0,487.0,5,6,2,4.0,0.00,...,False,False,False,False,False,False,False,True,False,True
44,35.0,37,4600.0,5114.0,656.0,2,1,0,5.0,0.00,...,False,False,False,False,True,True,False,True,True,False
45,50.0,67,1774.0,541.0,753.0,1,0,0,3.0,16.99,...,False,False,True,False,True,True,False,True,False,True
46,36.0,45,1963.0,964.0,534.0,2,2,1,1.0,0.00,...,False,False,False,False,False,False,False,False,True,False
47,32.0,40,4399.0,3641.0,645.0,4,1,0,3.0,0.00,...,False,False,False,False,True,True,False,True,True,False
48,24.0,39,1510.0,1768.0,691.0,1,2,2,1.0,0.00,...,False,False,False,False,True,False,False,True,False,False
49,42.0,75,4700.0,1641.0,668.0,4,2,0,3.0,0.00,...,False,False,False,False,False,False,False,True,True,False

In [53]:
print('Original shape:', df.shape)
print('Prepared shape before encoding:', clean_df.shape)
print('Shape after encoding:', df_encoded.shape)

Original shape: (1200, 23)
Prepared shape before encoding: (1200, 24)
Shape after encoding: (1200, 40)

In [54]:
list(df_encoded.columns)

['age',
 'tenure_months',
 'monthly_income',
 'avg_monthly_balance',
 'credit_score',
 'num_products',
 'customer_service_calls',
 'missed_payments_6m',
 'support_rating',
 'monthly_fees',
 'digital_engagement_score',
 'loan_amount',
 'loan_term_months',
 'debt_to_income_ratio',
 'interest_rate',
 'loan_repaid',
 'credit_score_was_missing',
 'monthly_income_was_missing',
 'region_London',
 'region_North East',
 'region_North West',
 'region_Northern Ireland',
 'region_Scotland',
 'region_South East',
 'region_South West',
 'region_Unknown',
 'region_Wales',
 'region_West Midlands',
 'region_Yorkshire and the Humber',
 'account_type_Everyday',
 'account_type_Plus',
 'account_type_Premium',
 'account_type_Unknown',
 'has_credit_card_Unknown',
 'has_credit_card_Yes',
 'has_crypto_wallet_Yes',
 'uses_mobile_app_Unknown',
 'uses_mobile_app_Yes',
 'contract_type_Monthly',
 'contract_type_No fixed term']

In [55]:
df_encoded.isnull().sum().sum()

np.int64(0)

In [56]:
df_encoded.select_dtypes(include='object').columns.tolist()

[]

In [57]:
df_model_ready = df_encoded.copy()

df_model_ready.head()

,age,tenure_months,monthly_income,avg_monthly_balance,credit_score,num_products,customer_service_calls,missed_payments_6m,support_rating,monthly_fees,...,account_type_Plus,account_type_Premium,account_type_Unknown,has_credit_card_Unknown,has_credit_card_Yes,has_crypto_wallet_Yes,uses_mobile_app_Unknown,uses_mobile_app_Yes,contract_type_Monthly,contract_type_No fixed term
0,36.0,24,2281.0,1702.0,637.0,3,3,0,5.0,16.99,...,False,True,False,False,True,False,False,False,False,False
1,47.0,13,4747.0,3045.0,655.0,1,2,0,4.0,16.99,...,False,True,False,False,True,False,False,False,True,False
2,44.0,41,5605.0,5230.0,583.0,2,0,0,2.0,16.99,...,False,True,False,False,True,False,False,True,False,True
3,49.0,23,5576.0,7223.0,850.0,3,2,1,4.0,16.99,...,False,True,False,False,True,True,False,True,True,False
4,32.0,63,4737.0,4982.0,691.0,1,1,3,4.0,0.00,...,False,False,False,False,False,True,False,True,False,True

In [58]:
print('Missing values left:', df_model_ready.isnull().sum().sum())
print('Text columns left:', list(df_model_ready.select_dtypes(include='object').columns))
print('Final shape:', df_model_ready.shape)
print('Customer ID still present:', 'customer_id' in df_model_ready.columns)

Missing values left: 0
Text columns left: []
Final shape: (1200, 40)
Customer ID still present: False

In [59]:
clean_file_path = 'codebar-AI-fundamentals-pixels-banking-ML-model/data/pixels_banking_loan_repayment_clean.csv'

# 2. Save it
print('Saving clean data to:', clean_file_path)
df_model_ready.to_csv(clean_file_path, index=False)

Saving clean data to: codebar-AI-fundamentals-pixels-banking-ML-model/data/pixels_banking_loan_repayment_clean.csv

In [60]:
!ls "codebar-AI-fundamentals-pixels-banking-ML-model/data/"

pixels_banking_loan_repayment_capstone_dataset.csv
pixels_banking_loan_repayment_clean.csv